#!/bin/sh

# Lint php code.

# We only lint files from the site directory, ingnoring the libraries.
include='^(src|tests)/.*\.php'
exclude=' '

# The linter path is relative to the root of the repository.
relative=1
linter="vendor/bin/phpcs"
options='-p --report=full --standard=phpcs.xml'
message='Linting staged PHP files (coding standards)...'

# Docksal compatibility.
if [ -x "$(command -v fin)" ]; then
  linter="phpcs"
fi

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
