#!/bin/sh

# Lint php code.

# We only lint files from the site directory, ingnoring the libraries.
include='^(src|tests)/.*\.php'
exclude=' '

# Assume that the php command is global.
linter="php"
options='-l'
message='Linting staged PHP files (syntax)...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
